/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login User */
        post: operations["login_user_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: operations["logout_user_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Token */
        get: operations["verify_token_v1_auth_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Info */
        get: operations["get_current_user_info_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telemetry History */
        get: operations["get_telemetry_history_v1_telemetry_get"];
        put?: never;
        /** Ingest Telemetry */
        post: operations["ingest_telemetry_v1_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Session Results */
        get: operations["list_session_results_v1_sessions_get"];
        put?: never;
        /** Create Session Result */
        post: operations["create_session_result_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_v1_calibration_get"];
        put?: never;
        /** Upsert Calibration */
        post: operations["upsert_calibration_v1_calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Calibration */
        Calibration: {
            /** Emgbaseline */
            emgBaseline: number;
            /** Emgmvc */
            emgMvc: number;
            /** Fsrzero */
            fsrZero: number;
            /** Fsrmax */
            fsrMax: number;
            /** User Id */
            user_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalibrationCreate */
        CalibrationCreate: {
            /** Emgbaseline */
            emgBaseline: number;
            /** Emgmvc */
            emgMvc: number;
            /** Fsrzero */
            fsrZero: number;
            /** Fsrmax */
            fsrMax: number;
        };
        /** DeviceState */
        DeviceState: {
            /** Board */
            board?: string | null;
            /** Connected */
            connected?: boolean | null;
            /** Lastseen */
            lastSeen?: number | null;
            /** Packetcount */
            packetCount?: number | null;
            /** Ratehz */
            rateHz?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** EmgState */
        EmgState: {
            /** Raw */
            raw?: number | null;
            /** Rawbuffer */
            rawBuffer?: number[] | null;
            /** Rms */
            rms?: number | null;
            /** Peak */
            peak?: number | null;
            /** Mvcpercent */
            mvcPercent?: number | null;
            /** Ishightension */
            isHighTension?: boolean | null;
            /** Timestamp */
            timestamp?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FsrState */
        FsrState: {
            /** Gripforce */
            gripForce?: number | null;
            /** Gripstability */
            gripStability?: number | null;
            /** Isstable */
            isStable?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MpuState */
        MpuState: {
            /** Pitch */
            pitch?: number | null;
            /** Roll */
            roll?: number | null;
            /** Velocity */
            velocity?: number | null;
            /** Ax */
            ax?: number | null;
            /** Ay */
            ay?: number | null;
            /** Az */
            az?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** RepResult */
        RepResult: {
            /** Repnumber */
            repNumber: number;
            /** Concentricvelocity */
            concentricVelocity: number;
            /** Rom */
            rom: number;
            /** Isclean */
            isClean: boolean;
            /** Velocitylosspercent */
            velocityLossPercent: number;
            /** Peakemg */
            peakEmg: number;
            /** Cheatreason */
            cheatReason?: string | null;
        };
        /** SessionResult */
        SessionResult: {
            /** Setnumber */
            setNumber: number;
            /** Exercise */
            exercise: string;
            /** Weightkg */
            weightKg: number;
            /** Durationseconds */
            durationSeconds: number;
            /** Totalreps */
            totalReps: number;
            /** Cleanreps */
            cleanReps: number;
            /** Cheatedreps */
            cheatedReps: number;
            /** Formpuritypercent */
            formPurityPercent: number;
            /** Effectivereps */
            effectiveReps: number;
            /** Hightensiontutseconds */
            highTensionTutSeconds: number;
            /** Reps */
            reps?: components["schemas"]["RepResult"][];
            /** Timestamp */
            timestamp?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionResultCreate */
        SessionResultCreate: {
            /** Setnumber */
            setNumber: number;
            /** Exercise */
            exercise: string;
            /** Weightkg */
            weightKg: number;
            /** Durationseconds */
            durationSeconds: number;
            /** Totalreps */
            totalReps: number;
            /** Cleanreps */
            cleanReps: number;
            /** Cheatedreps */
            cheatedReps: number;
            /** Formpuritypercent */
            formPurityPercent: number;
            /** Effectivereps */
            effectiveReps: number;
            /** Hightensiontutseconds */
            highTensionTutSeconds: number;
            /** Reps */
            reps?: components["schemas"]["RepResult"][];
            /** Timestamp */
            timestamp?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** TelemetryIngest */
        TelemetryIngest: {
            emg?: components["schemas"]["EmgState"] | null;
            fsr?: components["schemas"]["FsrState"] | null;
            mpu?: components["schemas"]["MpuState"] | null;
            vitals?: components["schemas"]["VitalsState"] | null;
            device?: components["schemas"]["DeviceState"] | null;
            /** Timestamp */
            timestamp?: number | null;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Avatar */
            avatar?: string | null;
            /** Roles */
            roles?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VitalsState */
        VitalsState: {
            /** Hr */
            hr?: number | null;
            /** Spo2 */
            spo2?: number | null;
            /** Skintemp */
            skinTemp?: number | null;
            /** Deltatemp */
            deltaTemp?: number | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    logout_user_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verify_token_v1_auth_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    get_current_user_info_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    get_telemetry_history_v1_telemetry_get: {
        parameters: {
            query?: {
                since?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_telemetry_v1_telemetry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIngest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_results_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_result_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_v1_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
        };
    };
    upsert_calibration_v1_calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
