/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login User */
        post: operations["login_user_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: operations["logout_user_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Token */
        get: operations["verify_token_v1_auth_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Info */
        get: operations["get_current_user_info_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Everyone else the caller can compare themselves with, most recently active first.
         */
        get: operations["list_users_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Performance
         * @description Any user's saved sets (the caller's own included) for the user-vs-user comparison.
         *
         *     Not limited by the plan's history window, so both sides are compared over the same span.
         */
        get: operations["get_user_performance_v1_users__user_id__performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telemetry History */
        get: operations["get_telemetry_history_v1_telemetry_get"];
        put?: never;
        /** Ingest Telemetry */
        post: operations["ingest_telemetry_v1_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Session Results */
        get: operations["list_session_results_v1_sessions_get"];
        put?: never;
        /** Create Session Result */
        post: operations["create_session_result_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare With Previous Session
         * @description The given session next to the same user's previous one (by start time).
         *
         *     Deliberately not limited by the plan's history window: the post-workout comparison
         *     must always find the previous session, however long ago it was.
         */
        get: operations["compare_with_previous_session_v1_sessions__session_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_v1_calibration_get"];
        put?: never;
        /** Upsert Calibration */
        post: operations["upsert_calibration_v1_calibration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing Config */
        get: operations["get_billing_config_v1_billing_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing Overview */
        get: operations["get_billing_overview_v1_billing_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout */
        post: operations["checkout_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Subscription
         * @description Re-check a pending (3-D Secure) charge -- used when returning from the bank page,
         *     and the only way it completes in local dev where Omise webhooks can't reach us.
         */
        post: operations["refresh_subscription_v1_billing_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Subscription */
        post: operations["cancel_subscription_v1_billing_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Subscription */
        post: operations["resume_subscription_v1_billing_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/webhooks/omise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Omise Webhook */
        post: operations["omise_webhook_v1_billing_webhooks_omise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BillingConfig */
        BillingConfig: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "disabled" | "mock" | "omise";
            /** Omisepublickey */
            omisePublicKey?: string | null;
            /** Plans */
            plans: components["schemas"]["Plan"][];
        };
        /** BillingOverview */
        BillingOverview: {
            plan: components["schemas"]["Plan"];
            subscription: components["schemas"]["Subscription"] | null;
        };
        /** Calibration */
        Calibration: {
            /** Emgbaseline */
            emgBaseline: number;
            /** Emgmvc */
            emgMvc: number;
            /** Fsrzero */
            fsrZero: number;
            /** Fsrmax */
            fsrMax: number;
            /**
             * Emgreponpct
             * @default 35
             */
            emgRepOnPct: number;
            /**
             * Emgrepoffpct
             * @default 20
             */
            emgRepOffPct: number;
            /**
             * Emgreppeakpct
             * @default 45
             */
            emgRepPeakPct: number;
            /** User Id */
            user_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalibrationCreate */
        CalibrationCreate: {
            /** Emgbaseline */
            emgBaseline: number;
            /** Emgmvc */
            emgMvc: number;
            /** Fsrzero */
            fsrZero: number;
            /** Fsrmax */
            fsrMax: number;
            /**
             * Emgreponpct
             * @default 35
             */
            emgRepOnPct: number;
            /**
             * Emgrepoffpct
             * @default 20
             */
            emgRepOffPct: number;
            /**
             * Emgreppeakpct
             * @default 45
             */
            emgRepPeakPct: number;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Planid */
            planId: string;
            /** Cardtoken */
            cardToken?: string | null;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            subscription: components["schemas"]["Subscription"];
            /** Authorizeuri */
            authorizeUri?: string | null;
        };
        /** DeviceState */
        DeviceState: {
            /** Board */
            board?: string | null;
            /** Connected */
            connected?: boolean | null;
            /** Lastseen */
            lastSeen?: number | null;
            /** Packetcount */
            packetCount?: number | null;
            /** Ratehz */
            rateHz?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** EmgState */
        EmgState: {
            /** Raw */
            raw?: number | null;
            /** Rawbuffer */
            rawBuffer?: number[] | null;
            /** Rms */
            rms?: number | null;
            /** Peak */
            peak?: number | null;
            /** Mvcpercent */
            mvcPercent?: number | null;
            /** Ishightension */
            isHighTension?: boolean | null;
            /** Timestamp */
            timestamp?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FsrState */
        FsrState: {
            /** Gripforce */
            gripForce?: number | null;
            /** Gripstability */
            gripStability?: number | null;
            /** Isstable */
            isStable?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MpuState */
        MpuState: {
            /** Pitch */
            pitch?: number | null;
            /** Roll */
            roll?: number | null;
            /** Velocity */
            velocity?: number | null;
            /** Ax */
            ax?: number | null;
            /** Ay */
            ay?: number | null;
            /** Az */
            az?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** Plan */
        Plan: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Pricesatang */
            priceSatang: number;
            /** Currency */
            currency: string;
            /** Interval */
            interval: string;
            features: components["schemas"]["PlanFeatures"];
        };
        /** PlanFeatures */
        PlanFeatures: {
            /** Historydays */
            historyDays: number | null;
        };
        /** PublicUser */
        PublicUser: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Avatar */
            avatar?: string | null;
            /**
             * Sessioncount
             * @default 0
             */
            sessionCount: number;
            /**
             * Setcount
             * @default 0
             */
            setCount: number;
            /** Lastworkoutat */
            lastWorkoutAt?: string | null;
        };
        /** RepResult */
        RepResult: {
            /** Repnumber */
            repNumber: number;
            /** Concentricvelocity */
            concentricVelocity: number;
            /** Rom */
            rom: number;
            /** Isclean */
            isClean: boolean;
            /** Velocitylosspercent */
            velocityLossPercent: number;
            /** Peakemg */
            peakEmg: number;
            /** Cheatreason */
            cheatReason?: string | null;
        };
        /** SessionComparison */
        SessionComparison: {
            /** Current */
            current: components["schemas"]["SessionResult"][];
            /** Previous */
            previous: components["schemas"]["SessionResult"][];
        };
        /** SessionResult */
        SessionResult: {
            /** Setnumber */
            setNumber: number;
            /** Exercise */
            exercise: string;
            /** Weightkg */
            weightKg: number;
            /** Durationseconds */
            durationSeconds: number;
            /** Totalreps */
            totalReps: number;
            /** Cleanreps */
            cleanReps: number;
            /** Cheatedreps */
            cheatedReps: number;
            /** Formpuritypercent */
            formPurityPercent: number;
            /** Effectivereps */
            effectiveReps: number;
            /** Hightensiontutseconds */
            highTensionTutSeconds: number;
            /** Reps */
            reps?: components["schemas"]["RepResult"][];
            /** Timestamp */
            timestamp?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Repsource */
            repSource?: string | null;
            /** Emgmvcuv */
            emgMvcUv?: number | null;
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionResultCreate */
        SessionResultCreate: {
            /** Setnumber */
            setNumber: number;
            /** Exercise */
            exercise: string;
            /** Weightkg */
            weightKg: number;
            /** Durationseconds */
            durationSeconds: number;
            /** Totalreps */
            totalReps: number;
            /** Cleanreps */
            cleanReps: number;
            /** Cheatedreps */
            cheatedReps: number;
            /** Formpuritypercent */
            formPurityPercent: number;
            /** Effectivereps */
            effectiveReps: number;
            /** Hightensiontutseconds */
            highTensionTutSeconds: number;
            /** Reps */
            reps?: components["schemas"]["RepResult"][];
            /** Timestamp */
            timestamp?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Repsource */
            repSource?: string | null;
            /** Emgmvcuv */
            emgMvcUv?: number | null;
        };
        /** Subscription */
        Subscription: {
            /** Planid */
            planId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "incomplete" | "active" | "past_due" | "canceled";
            /** Provider */
            provider: string;
            /** Currentperiodstart */
            currentPeriodStart?: string | null;
            /** Currentperiodend */
            currentPeriodEnd?: string | null;
            /**
             * Cancelatperiodend
             * @default false
             */
            cancelAtPeriodEnd: boolean;
            /** Lasterror */
            lastError?: string | null;
        };
        /** TelemetryIngest */
        TelemetryIngest: {
            emg?: components["schemas"]["EmgState"] | null;
            fsr?: components["schemas"]["FsrState"] | null;
            mpu?: components["schemas"]["MpuState"] | null;
            vitals?: components["schemas"]["VitalsState"] | null;
            device?: components["schemas"]["DeviceState"] | null;
            /** Timestamp */
            timestamp?: number | null;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Avatar */
            avatar?: string | null;
            /** Roles */
            roles?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /** UserPerformance */
        UserPerformance: {
            user: components["schemas"]["PublicUser"];
            /** Sets */
            sets: components["schemas"]["SessionResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VitalsState */
        VitalsState: {
            /** Hr */
            hr?: number | null;
            /** Spo2 */
            spo2?: number | null;
            /** Skintemp */
            skinTemp?: number | null;
            /** Deltatemp */
            deltaTemp?: number | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    logout_user_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verify_token_v1_auth_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    get_current_user_info_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"][];
                };
            };
        };
    };
    get_user_performance_v1_users__user_id__performance_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPerformance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_history_v1_telemetry_get: {
        parameters: {
            query?: {
                since?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_telemetry_v1_telemetry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIngest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_results_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_result_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_with_previous_session_v1_sessions__session_id__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_v1_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
        };
    };
    upsert_calibration_v1_calibration_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_billing_config_v1_billing_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfig"];
                };
            };
        };
    };
    get_billing_overview_v1_billing_subscription_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingOverview"];
                };
            };
        };
    };
    checkout_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_subscription_v1_billing_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingOverview"];
                };
            };
        };
    };
    cancel_subscription_v1_billing_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingOverview"];
                };
            };
        };
    };
    resume_subscription_v1_billing_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingOverview"];
                };
            };
        };
    };
    omise_webhook_v1_billing_webhooks_omise_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
